export const citiesArray: Array<string> = [
    "Warsaw",
    "Dubai",
    "Paris",
    "Moscow",
    "Sydney",
    "L.A.",
    "Rio de Janeiro",
    "Washington",
    "Amsterdam",
    "Athens",
    "Barcelona",
    "Berlin",
    "Genewa",
    "Copenhagen",
    "Lisbon",
    "London",
    "Madrid",
    "Cracow",
    "Wroclaw",
    "Oslo",
    "Rome",
    "Vienna",
    "Stockholm",
    "Venice",
    "Melbourne",
    "Shanghai",
    "Cairo",
    "Tel Aviv",
    "Chicago",
    "Las Vegas",
    "Quebec",
  ];