export const WEATHER:Object = {
    WEATHER_FETCH: "WEATHER_FETCH",
    WEATHER_FETCH_SUCCESS: "WEATHER_FETCH_SUCCESS",
    WEATHER_FETCH_ERROR: "WEATHER_FETCH_ERROR"
}

export const CITIES:Object = {
    CITIES_FETCH: "CITIES_FETCH",
    CITIES_FETCH_SUCCESS: "CITIES_FETCH_SUCCESS",
    CITIES_FETCH_ERROR: "CITIES_FETCH_ERROR"
}